-- =====================================================================
-- Kalasag: Supabase database
-- Run once in Supabase: SQL Editor > New query > paste this file > Run.
-- The website (website/app.py) adds the demo data itself the first time
-- it starts, so there is no separate seed file.
--
-- Only the website talks to this database, using the SECRET key.
-- Row level security is on for every table with no public rules, so the
-- publishable key cannot read or change anything.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Remove the earlier version of the tables (safe if they don't exist)
-- ---------------------------------------------------------------------
drop trigger if exists on_auth_user_created on auth.users;
drop view if exists report_daily_stats, lexicon_review_queue cascade;
drop table if exists incident_files, incidents, alerts, reports, events, leaders,
  lexicon_audit, lexicon_entries, lexicon, next_steps, platform_reporting, legal_info,
  profiles, organizations, subtypes, categories, languages, countries cascade;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.touch_updated_at() cascade;
drop function if exists public.lexicon_before_write() cascade;
drop function if exists public.lexicon_log_change() cascade;
drop function if exists public.reports_before_write() cascade;
drop function if exists public.incident_files_no_edit() cascade;
drop function if exists public.current_app_role() cascade;
drop function if exists public.is_admin() cascade;
drop function if exists public.my_org_id() cascade;
drop function if exists public.is_verified_reviewer() cascade;
drop function if exists public.can_access_leader(uuid) cascade;
drop function if exists public.incident_leader(uuid) cascade;
drop function if exists public.lexicon_export(text, text[]) cascade;
drop function if exists public.popup_info(text) cascade;
drop function if exists public.match_leaders(text) cascade;
drop function if exists public.run_spike_check(numeric, int, interval) cascade;
drop function if exists public.inject_demo_reports(uuid, int) cascade;
drop function if exists public.clear_demo_data() cascade;


-- ---------------------------------------------------------------------
-- Categories: two levels.
--   broad = the 4 categories from the team's guide
--   code  = the detailed label the extension and website use
-- ---------------------------------------------------------------------
create table categories (
  code        text primary key,
  label       text not null,
  broad       text not null check (broad in
                ('gender_hate_speech', 'gendered_disinformation', 'manipulated_text', 'none', 'unclassified')),
  broad_label text not null,
  sort_order  smallint not null
);

insert into categories (code, label, broad, broad_label, sort_order) values
  ('sexualized_slur',             'Sexualized slur',                          'gender_hate_speech',      'Gender hate speech',      1),
  ('emotional_unfitness',         'False ''too emotional to lead'' narrative', 'gender_hate_speech',      'Gender hate speech',      2),
  ('family_role',                 '''Belongs at home'' attack',                'gender_hate_speech',      'Gender hate speech',      3),
  ('appearance',                  'Attack on appearance',                     'gender_hate_speech',      'Gender hate speech',      4),
  ('misogynistic_generalization', 'Demeaning women as a group',               'gender_hate_speech',      'Gender hate speech',      5),
  ('threat',                      'Threat of violence',                       'gender_hate_speech',      'Gender hate speech',      6),
  ('competence_undermining',      '''Puppet'' or incompetence narrative',      'gendered_disinformation', 'Gendered disinformation', 7),
  ('fabricated_scandal',          'Fabricated scandal',                       'gendered_disinformation', 'Gendered disinformation', 8),
  ('unclassified',                'Needs classification',                     'unclassified',            'Not yet classified',      9);


-- ---------------------------------------------------------------------
-- Word database (lexicon)
-- ---------------------------------------------------------------------
create table lexicon (
  id             bigint generated by default as identity primary key,
  term           text not null,
  variants       text[] not null default '{}',
  language       text not null,                  -- tl, ceb, ilo, en
  country        text not null default 'PH',
  meaning        text,
  category       text not null default 'unclassified' references categories (code),
  severity       text not null default 'medium' check (severity in ('low', 'medium', 'high')),
  context_note   text,
  status         text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  raw_submission text,
  submitted_by   text,
  approved_by    text,
  ai_drafted     boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index lexicon_status on lexicon (status, country, language);

-- Every change to the word list is logged, so a removed or edited word
-- can always be traced and restored
create table lexicon_audit (
  id         bigint generated always as identity primary key,
  lexicon_id bigint not null,
  action     text not null,
  old_row    jsonb,
  new_row    jsonb,
  changed_at timestamptz not null default now()
);

create or replace function public.lexicon_log_change()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into lexicon_audit (lexicon_id, action, old_row, new_row)
  values (coalesce(new.id, old.id), lower(tg_op),
          case when tg_op <> 'INSERT' then to_jsonb(old) end,
          case when tg_op <> 'DELETE' then to_jsonb(new) end);
  return null;
end $$;

create trigger lexicon_audit_log
  after insert or update or delete on lexicon
  for each row execute function public.lexicon_log_change();


-- ---------------------------------------------------------------------
-- Leaders and their upcoming events
-- ---------------------------------------------------------------------
create table leaders (
  id            bigint generated by default as identity primary key,
  name          text not null,
  name_variants text[] not null default '{}',   -- nicknames, surname only, titles
  organization  text,
  alert_contact text,
  created_at    timestamptz not null default now()
);

create table events (
  id         bigint generated by default as identity primary key,
  leader_id  bigint not null references leaders (id) on delete cascade,
  name       text not null,
  event_date date,
  location   text,
  created_at timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- Reports sent by the extension ("Save as evidence")
-- ---------------------------------------------------------------------
create table reports (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  url               text,
  platform          text,
  lexicon_id        bigint references lexicon (id) on delete set null,
  matched_text      text,
  context_text      text,
  category          text not null default 'unclassified' references categories (code),
  reporter_role     text,
  country           text not null default 'PH',
  leader_id         bigint references leaders (id) on delete set null,
  screenshot_file   text,
  screenshot_sha256 text check (screenshot_sha256 is null or screenshot_sha256 ~ '^[0-9a-f]{64}$')
);
create index reports_leader_time on reports (leader_id, created_at);
create index reports_time on reports (created_at);

-- A saved screenshot and its fingerprint can never be changed afterwards
create or replace function public.reports_lock_evidence()
returns trigger language plpgsql
as $$
begin
  if old.screenshot_sha256 is not null
     and (new.screenshot_sha256 is distinct from old.screenshot_sha256
          or new.screenshot_file is distinct from old.screenshot_file) then
    raise exception 'Evidence is locked: the screenshot and its fingerprint cannot be changed';
  end if;
  return new;
end $$;

create trigger reports_lock_evidence
  before update on reports
  for each row execute function public.reports_lock_evidence();


-- ---------------------------------------------------------------------
-- Early-warning alerts and incident documentation
-- ---------------------------------------------------------------------
create table alerts (
  id               bigint generated by default as identity primary key,
  leader_id        bigint not null references leaders (id) on delete cascade,
  created_at       timestamptz not null default now(),
  count_24h        int,
  baseline_per_day numeric(8, 2),
  summary          text,
  seen             boolean not null default false
);

create table incidents (
  id          bigint generated by default as identity primary key,
  leader_id   bigint references leaders (id) on delete set null,
  created_at  timestamptz not null default now(),
  occurred_at timestamptz,
  description text not null,
  witnesses   text,
  files       jsonb not null default '[]'        -- [{name, file, sha256}]
);


-- ---------------------------------------------------------------------
-- Security: only the website (secret key) can use these tables
-- ---------------------------------------------------------------------
alter table categories    enable row level security;
alter table lexicon       enable row level security;
alter table lexicon_audit enable row level security;
alter table leaders       enable row level security;
alter table events        enable row level security;
alter table reports       enable row level security;
alter table alerts        enable row level security;
alter table incidents     enable row level security;

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;


-- ---------------------------------------------------------------------
-- Private file storage for screenshots, photos and voice notes
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('evidence', 'evidence', false, 52428800)   -- 50 MB per file
on conflict (id) do nothing;
